### ISSUE TITLE
Error: no plugin found for stars_rating.less in barbatus:stars-rating; a plugin for *.less was active when it was published but none is now

### ISSUE THREAD

**Issue by rodrigooler** [barbatus/stars-rating#14]
When you run the command meteor add barbatus installation: stars- rating is installed normally, but when running the meteor it displays the following error below:

=> A patch (Meteor 1.4.0.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
Started MongoDB.
Errors prevented startup:

While building for web.browser:
error: no plugin found for stars_rating.less in barbatus:stars-rating; a plugin for *.less was active when it was published but none is now

Your application has errors. Waiting for file change.

**Comment by maglioandre** [comment]
I'm having the same problem , the component installs normally, but when you run the command "meteor" to start the application , it displays the error: 

   While building for web.browser:
   error: no plugin found for stars_rating.less in barbatus:stars-rating; a plugin for *.less was active when it was published but none is now

Any suggestion?
Thank you very much.

**Comment by dilldill1** [comment]
I'm having the same problem , the component installs normally, but when you run the command "meteor" to start the application , it displays the error:

While building for web.browser:
error: no plugin found for stars_rating.less in barbatus:stars-rating; a plugin for *.less was active when it was published but none is now

Any help would be great. thanks

**Comment by reyesreg** [comment]
I'm having the exact same problem. Can anybody shed some light?

**Comment by maglioandre** [comment]
Goodnight everyone, after a long search i got a solution to our problem. 
In the windows powershell, enter the command: npm install meteor --global windows-build-tools --production 
And after a long and time-consuming installation packages, you can try to use the starsRating component that will work.
I hope it helps.
Hugs

**Comment by ddiviacchi** [comment]
Hi Maglioandre,
I tried this and Python & Visual Studio load okay, but it looks like it then fails out on install of node.js
fibers. Any thoughts on how I could fix this? thanks

![image](https://cloud.githubusercontent.com/assets/3903965/17476628/df3a035e-5d58-11e6-9193-34acaef844c6.png)

**Comment by dilldill1** [comment]
Hi Maglioandre,  
I run this command and Python & Visual Studio Build tools successfully load.  However, it then fails out on what looks like is installing node.js fibers. Any thoughts how to fix this? thanks

![image](https://cloud.githubusercontent.com/assets/3903965/17476700/3d1a9a38-5d59-11e6-990b-65b484d2f913.png)

**Comment by barbatus** [comment]
It seems to be Windows specific issue since I just upgraded the demo to Meteor 1.4.0.1 and don't see any issue (on Mac). There might be problem with Meteor upgrade itself. So I'd recommend to reinstall Meteor.

**Comment by LanQ** [comment]
same issue happens on me.  and it still there after reinstall
- windows 7 x64
- meteor 1.4.0.1

**Comment by 1ns1d3r** [comment]
same issue.

```
Ubuntu 14.04 LTS x64
meteor 1.4.0.1
```

**Comment by JasemQabazard** [comment]
After I run your command maglioandre on windows 10
it failed just like ddiviacchi explains
but then something wearied happens when I run meteor 

# it looks for it in a roaming directory instead of local, can not seem to fix it even after uninstall and install meteor

D:\MobileApps\Meteor_CourseRA\image_share>meteor
module.js:327
    throw err;
    ^
Error: Cannot find module 'C:\Users\Jasem Qabazard\AppData\Roaming\npm\node_modules\meteor\app\meteor\meteor.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by maglioandre** [comment]
Goodnight everyone, I not had this problem with the fibers, I'm searching to see if I can help, for now my suggestions are:
Reinstall meteor
Try to install / update only the fibers to version 1.0.8, which seems to be the last. (npm install fibers)
And try to run the command that I mentioned before.
It may help in something, if I find any other possible solution I post here.
Hugs

**Comment by dilldill1** [comment]
I have tried installing node.js based on another article, reinstalling meteor, both which worked but did not fix anything.  I also tried installing/updating fibers (along with @1.0.8) but both fail for me.

**Comment by andyza** [comment]
_resolved_ 

I had the same issue.
The problem was that the *less version was not compatible. If you run 'meteor update' you'll see a number of plugins that need to be updated. Try running 'meteor update less'. That worked for me.

MacOS 10.11.5
meteor 1.4.0.1

**Comment by rodrigooler** [comment]
In fact the problem was with the version of the less it was not compatible with the version of meteor update as personal indicated above, If you have compatibility problems with your operating system to create a new issue telling the description of it with version.

//Command that solves the problem
meteor update
