### ISSUE TITLE
[Question] How to set a default rating without triggering the 'change' event ?

### ISSUE THREAD

**Issue by Ilshidur** [barbatus/stars-rating#17]
It's all in the title. I just want to set the default rating to the value the user set before.

Use case :
- the user sets a rating
- reloads the page
- the previous rating is retrieved from the database
- the user sees the rating he has set, even after refreshing the page

How can I manage to achieve this ?

**Comment by shamsahmed** [comment]
I want to know the same.. @Ilshidur did you get a solution?
I basically stored the user click in my own collection and want to show the value from my collection on the screen.
How do you set the star rating to a value. Example if i pass 3; three starts would be active.

**Comment by Ilshidur** [comment]
I did not find a workaround for this, sorry.
My "solution" was to add a "Submit rate" button below the stars and to set a 'click' listener on this. Therefore, I could set the user vote in the 'onRendering' template function. In this case, I didn't use the 'change' event of this control.

**Comment by adamgins** [comment]
FYI, I kind of hacked my way around this as was getting a kind of infinite loop. Here's the psuedo-concept:
1. When the template `isCreated` I create a reactiveVar that waits (`autorun`) for the data.
2. I use the `onChange` even to set the reactiveVar
3. when the template (with the rating widget) is `onDestroyed` I then set the database value to the value stored
   
   in the reactiveVar.

So this breaks the `onChange` firing (which it would if you had it wired to the database value).
