### ISSUE TITLE
meteor fails to start after adding package

### ISSUE THREAD

**Issue by pgen2** [barbatus/stars-rating#18]
After adding the package via:

> meteor add barbatus:stars-rating

Meteor will no longer start due to a missing plugin, described in the error given below:

=> Errors prevented startup:

   While building for web.browser:
   error: no plugin found for stars_rating.less in barbatus:stars-rating; a plugin for *.less was active when it
   was published but none is now

Is there a known work around for this ?

**Comment by pgen2** [comment]
Problem was the version of less installed, updated less with

> meteor update less

Problem solved!

**Comment by enkkumiksu** [comment]
Hi I have the same problem.  less update doesn't solve it.  Any other suggestions?

**Comment by koloboid** [comment]
+1 have same error.
