### ISSUE TITLE
Stars disappear if _id starts with a number  

### ISSUE THREAD

**Issue by mgkaradag** [barbatus/stars-rating#19]
Stars disappear from window if _id (Mongo.Collection) in the same div starts with a number.   
<div class="caption">
A sample HTML and a screenshot are given below
      <h3>Rated {{rate}}</h3>
          <p>Description of the image</p>
            <p>{{>starsRating mutable=true class='js-img-rating' id=_id}} </p>
          <button class="js-delete-image btn btn-warning">delete</button>
</div>

![image](https://cloud.githubusercontent.com/assets/7791738/24115671/c8daa2ee-0dac-11e7-8b87-64157ab6919c.png)

**Comment by paulbrab** [comment]
This question might help http://stackoverflow.com/questions/5672903/can-i-have-a-div-with-id-as-number

I prefix the id as a work around by using a template helper
