### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by paulbrab** [barbatus/stars-rating#4]
Your package appears to be broken in IE 11.

Edit: seems to be versions 9 and up

**Comment by paulbrab** [comment]
By broken, I mean that the stars do not display.

Rendered css in IE is:
 `#stars_1 .star-glyph:before {
    content: "normal";
}`

instead of: 
`#stars_1 .star-glyph:before {
    content: "★";
}`

My workaround for now is:
`.star-glyph:before, .percent:before {
    content: '\2605'!important;
}`

**Comment by barbatus** [comment]
@paulbrab Now seems to be fixed, please check it out. I tested in IE11 only.
I somehow didn't notice it before that IE returns 'normal' for the content style.
It seems to be no way now to customize star symbol with CSS, so I just added star property to the template to reconfigure star symbol if needed.

**Comment by paulbrab** [comment]
Thanks @barbatus
