### ISSUE TITLE
less compatibility

### ISSUE THREAD

**Issue by jackkav** [barbatus/stars-rating#5]
Update to release METEOR@1.2.0.1 is impossible:
While selecting package versions:
error: Conflict: Constraint less@1.0.11 is not satisfied by less 2.5.0_2.
Constraints on package "less":
- less@=2.5.0_2 <- top level
- less@1.0.12 <- barbatus:stars-rating 1.0.2

**Comment by sebastianconcept** [comment]
+1

**Comment by barbatus** [comment]
@jackkav Thanks for you PR, but lets keep it from initial version for now.
I've just updated LESS version to be compatible with Meteor 1.2.
Please update package to new version.
Thanks.
